#ifndef PLAYERID_H_INCLUDED
#define PLAYERID_H_INCLUDED

namespace decore {

/**
 * @brief Player identifier for the Engine
 *
 * The id is generated by the Engind, see Engine::add(Player&).
 * The engine guarantees that same ids will have same pointer always.
 */
class PlayerId
{
};

}

#endif // PLAYERID_H_INCLUDED
